// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

namespace Biters
{

	public enum MapEvent : int {

		/*
		 * A custom map event.
		 */
		Custom = -1,

		//Map
		/*
		 * Called when the map is initialized.
		 */
		Init = 0,

		/*
		 * Called when the map reset itself.
		 */
		Reset = 1,
		
		/*
		 * Called when the map is stopped.
		 */
		Stop = 2,

		//Entities
		/*
		 * Called when an entity is added.
		 */
		AddEntity = 10,
		
		/*
		 * Called when an entity is removed.
		 */
		RemoveEntity = 11,

		//Tiles

		//TODO: Add other possible map event types.

	}
	
	public static class MapEventEnumInfo
	{
		
		//Extension of WorldDirection enum with static functinon.
		public static string EventName(this MapEvent Event)
		{
			string name;

			switch (Event) {
			case MapEvent.Init: name = "map_init_event"; break;
			case MapEvent.Reset: name = "map_reset_event"; break;
			default:
				name = "map_custom_event"; break;
			}
			
			return name;
		}
		
	}

	public class MapEventInfo : EventInfo {

		private MapEvent mapEvent;
		private Map<MapTile> map;

		//Optional Entity associated with the event.
		private MapEntity entity;

		//Optional Position associated with the event.
		private WorldPosition? position;
		
		public MapEventInfo(MapEvent MapEvent, Map<MapTile> Map) {
			this.mapEvent = MapEvent;
			this.map = Map;
		}
		
		public MapEventInfo(MapEvent MapEvent, Map<MapTile> Map, MapEntity Entity) : this (MapEvent, Map) {
			this.entity = Entity;
		}

		public MapEventInfo(MapEvent MapEvent, Map<MapTile> Map, WorldPosition position) : this (MapEvent, Map) {
			this.position = position;
		}

		public string EventName {
			get {
				return mapEvent.EventName();
			}
		}

		public MapEvent Event {

			get {
				return mapEvent;
			}

		}

		public Map<MapTile> Map {

			get {
				return map;
			}

		}

		public MapEntity Entity {

			get {
				return entity;
			}

		}

		public WorldPosition? Position {

			get {
				return position;
			}

		}

	}

}

